const MediaQuery = () => {
  return (
    <div className="text-white bg-slate-600">
      <h1
        className="
                xsm:block 
                sm:hidden 
                md:hidden 
                lg:hidden 
                xl:hidden 
                2xl:hidden 
                3xl:hidden"
      >
        XSM
      </h1>
      <h1
        className="
                xsm:hidden
                sm:block 
                md:hidden 
                lg:hidden 
                xl:hidden 
                2xl:hidden 
                3xl:hidden"
      >
        SM
      </h1>
      <h1
        className="
                xsm:hidden
                sm:hidden
                md:block 
                lg:hidden 
                xl:hidden 
                2xl:hidden 
                3xl:hidden"
      >
        MD
      </h1>
      <h1
        className="
                xsm:hidden
                sm:hidden
                md:hidden
                lg:block 
                xl:hidden 
                2xl:hidden 
                3xl:hidden"
      >
        LG
      </h1>
      <h1
        className="
                xsm:hidden
                sm:hidden
                md:hidden
                lg:hidden
                xl:block 
                2xl:hidden 
                3xl:hidden"
      >
        XL
      </h1>
      <h1
        className="
                xsm:hidden
                sm:hidden
                md:hidden
                lg:hidden
                xl:hidden
                2xl:block 
                3xl:hidden"
      >
        2XL
      </h1>
      <h1
        className="
                xsm:hidden
                sm:hidden
                md:hidden
                lg:hidden
                xl:hidden
                2xl:hidden
                3xl:block"
      >
        3XL
      </h1>
    </div>
  );
};

export default MediaQuery;
